const q=(s,r=document)=>r.querySelector(s); const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const header=q('[data-header]');
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});
q('[data-menu]')?.addEventListener('click',e=>{const open=header.classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',String(open));});
qa('.site-header nav a').forEach(a=>a.addEventListener('click',()=>header.classList.remove('menu-open')));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');revealObserver.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -6%'});
qa('.reveal').forEach(el=>revealObserver.observe(el));
const split=q('[data-split]');
if(split && !matchMedia('(prefers-reduced-motion: reduce)').matches){const nodes=[...split.childNodes];nodes.forEach(node=>{if(node.nodeType===Node.TEXT_NODE && node.textContent.trim()){const frag=document.createDocumentFragment();node.textContent.split(/(\s+)/).forEach(part=>{if(!part)return;if(/\s+/.test(part)){frag.append(part);return;}const s=document.createElement('span');s.className='word';s.textContent=part;frag.append(s)});node.replaceWith(frag);}else if(node.nodeName==='EM'){const words=node.textContent.split(/(\s+)/);node.textContent='';words.forEach(part=>{if(/\s+/.test(part)){node.append(part);return;}const s=document.createElement('span');s.className='word';s.textContent=part;node.append(s)});}});qa('.hero-title .word').forEach((w,i)=>{w.animate([{opacity:0,transform:'translateY(38px) rotate(1.5deg)'},{opacity:1,transform:'none'}],{duration:720,delay:120+i*95,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'})});}
const heroMedia=q('[data-parallax] img');let raf=false;addEventListener('scroll',()=>{if(!heroMedia||raf||matchMedia('(prefers-reduced-motion: reduce)').matches)return;raf=true;requestAnimationFrame(()=>{const y=Math.min(scrollY,innerHeight);heroMedia.style.transform=`scale(1.03) translateY(${y*.025}px)`;raf=false})},{passive:true});
const careStage=q('[data-care-stage]'); const careProgress=q('[data-care-progress]');
let care={step:0,forWhom:null,need:null,urgency:null,contact:null};
const careSteps=[{title:'Für wen suchen Sie Unterstützung?',options:[['angehoerig','Für einen Angehörigen','Ich organisiere die nächsten Schritte.'],['selbst','Für mich selbst','Ich möchte mich orientieren.']]},{title:'Wobei wird gerade am meisten Hilfe gebraucht?',options:[['grundpflege','Pflege im Alltag','Unterstützung bei körperbezogenen Maßnahmen.'],['betreuung','Betreuung','Begleitung und Unterstützung im Alltag.'],['haushalt','Haushalt','Entlastung bei hauswirtschaftlichen Aufgaben.'],['unsicher','Noch unsicher','Ich möchte erst verstehen, was passen könnte.']]},{title:'Wie dringend ist die Situation?',options:[['sofort','Sehr dringend','Wir brauchen schnell Orientierung.'],['bald','In den nächsten Tagen / Wochen','Wir planen die nächsten Schritte.'],['info','Erst informieren','Noch kein konkreter Start.']]},{title:'Wie möchten Sie am liebsten weitermachen?',options:[['telefon','Telefonisch','Direkt mit CN sprechen.'],['rueckruf','Rückruf','Einen Rückrufwunsch vormerken.'],['nia','Mit Nia','Erst digital sortieren, dann weiter.']]}];
function careSummary(){const need={grundpflege:'Grundpflege / Alltag',betreuung:'Betreuung',haushalt:'Hauswirtschaft',unsicher:'noch unklar'}[care.need];const urgency={sofort:'dringend',bald:'in den nächsten Tagen / Wochen',info:'zur Orientierung'}[care.urgency];return `Sie suchen ${care.forWhom==='angehoerig'?'für einen Angehörigen':'für sich selbst'} Unterstützung. Schwerpunkt: ${need}. Zeitrahmen: ${urgency}.`;}
function renderCare(){if(!careStage)return;careProgress.style.width=`${Math.min((care.step+1)*25,100)}%`;if(care.step<4){const s=careSteps[care.step];const cls=s.options.length===3?'care-options three':'care-options';careStage.innerHTML=`<div class="care-question"><div class="care-count">0${care.step+1} / 04</div><div class="care-main"><h3>${s.title}</h3><div class="${cls}">${s.options.map(([v,t,d])=>`<button class="care-option" data-care-value="${v}"><strong>${t}</strong><span>${d}</span></button>`).join('')}</div></div></div>`;qa('[data-care-value]',careStage).forEach(btn=>btn.addEventListener('click',()=>{const v=btn.dataset.careValue;if(care.step===0)care.forWhom=v;if(care.step===1)care.need=v;if(care.step===2)care.urgency=v;if(care.step===3)care.contact=v;care.step++;renderCare()}));return;}const action=care.contact==='telefon'?`<a href="tel:+496996237272">Jetzt 069 96237272 anrufen</a>`:care.contact==='nia'?`<button data-care-chat>Mit Nia weitermachen</button>`:`<button data-care-chat data-book="callback">Rückrufwunsch vormerken</button>`;careStage.innerHTML=`<div class="care-result"><span class="result-label">IHRE ORIENTIERUNG</span><h3>Der nächste Schritt ist jetzt klarer.</h3><p>${careSummary()}</p><div class="care-result-actions">${action}<button data-care-reset>Neu starten</button></div></div>`;q('[data-care-reset]',careStage)?.addEventListener('click',()=>{care={step:0};renderCare()});q('[data-care-chat]',careStage)?.addEventListener('click',e=>openChat(e.currentTarget.dataset.book==='callback'?'callback':'care'));}
renderCare();
const jobStage=q('[data-job-stage]'); let job={step:0,qualification:null,start:null,contact:null};
const jobSteps=[{title:'Welche Qualifikation bringst du mit?',options:[['fachkraft','Pflegefachkraft'],['examiniert','Examiniert / vergleichbar'],['andere','Andere Qualifikation']]},{title:'Wann könntest du grundsätzlich starten?',options:[['sofort','Kurzfristig'],['monat','In 1–2 Monaten'],['spaeter','Später / offen']]},{title:'Wie soll CN dich am besten erreichen?',options:[['telefon','Telefon'],['mail','E-Mail'],['erstinfo','Erst mehr erfahren']]}];
function renderJob(){if(!jobStage)return;if(job.step<3){const s=jobSteps[job.step];jobStage.innerHTML=`<div class="job-question"><span>0${job.step+1} / 03</span><h3>${s.title}</h3><div class="job-options">${s.options.map(([v,t])=>`<button data-job-value="${v}">${t}<span>→</span></button>`).join('')}</div></div>`;qa('[data-job-value]',jobStage).forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.jobValue;if(job.step===0)job.qualification=v;if(job.step===1)job.start=v;if(job.step===2)job.contact=v;job.step++;renderJob()}));return;}const qual={fachkraft:'Pflegefachkraft',examiniert:'Examiniert / vergleichbar',andere:'Andere Qualifikation'}[job.qualification];const start={sofort:'kurzfristig',monat:'in 1–2 Monaten',spaeter:'später / offen'}[job.start];jobStage.innerHTML=`<div class="job-result"><span>DEIN ERSTER FIT</span><h3>${qual}</h3><p>Start: ${start}. Die aktuelle öffentliche CN-Ausschreibung ist für Pflegefachkräfte in Vollzeit und unbefristet. Abweichende Modelle werden nicht behauptet, sondern persönlich geklärt.</p><a href="mailto:info@cn-derpflegedienst.de?subject=Interesse%20Pflegefachkraft%20bei%20CN">Unkompliziert Kontakt aufnehmen →</a><button data-job-reset>Neu starten</button></div>`;q('[data-job-reset]',jobStage)?.addEventListener('click',()=>{job={step:0};renderJob()});}
renderJob();
const panel=q('[data-chat]'),backdrop=q('[data-chat-backdrop]'),chatBody=q('[data-chat-body]'),chatQuick=q('[data-chat-quick]');
function bot(text){chatBody.insertAdjacentHTML('beforeend',`<div class="chat-msg bot">${text}</div>`);chatBody.scrollTop=chatBody.scrollHeight}
function user(text){chatBody.insertAdjacentHTML('beforeend',`<div class="chat-msg user">${text}</div>`);chatBody.scrollTop=chatBody.scrollHeight}
function quick(items){chatQuick.innerHTML=items.map(([label,action])=>`<button data-chat-action="${action}">${label}</button>`).join('');qa('[data-chat-action]',chatQuick).forEach(b=>b.addEventListener('click',()=>handleChat(b.dataset.chatAction,b.textContent)))}
function resetChat(mode='start'){chatBody.innerHTML='';if(mode==='care'){bot(`Ich habe Ihre Pflege-Kompass-Angaben aus dieser Sitzung. ${care.urgency==='sofort'?'Da es dringend klingt, würde ich keine weiteren Schleifen bauen.':'Ich kann direkt beim nächsten Schritt weitermachen.'}`);quick([['CN anrufen','call'],['Rückruf vormerken','callback'],['Leistungen','services']]);return;}if(mode==='callback'){bot('Gern. Für die Demo können Sie einen Rückruf-Zeitraum vormerken. Es wird noch nichts live an CN übertragen.');quick([['Heute Nachmittag','slot-a'],['Morgen Vormittag','slot-b'],['Lieber direkt anrufen','call']]);return;}bot('Hallo, ich bin Nia – eine KI-Assistentin in dieser Konzeptdemo. Wobei darf ich Sie unterstützen?');quick([['Pflegebedarf','care'],['Leistungen','services'],['Rückruf / Termin','callback'],['Karriere','career']]);}
function handleChat(action,label){user(label);if(action==='care'){bot('Am schnellsten sortieren wir die Situation über den Pflege-Kompass. Wenn Sie ihn schon genutzt haben, kann ich die Angaben dieser Sitzung berücksichtigen.');quick([['Pflege-Kompass öffnen','goto-care'],['Direkt anrufen','call']]);}else if(action==='services'){bot('Öffentlich bestätigt sind für CN grundpflegerische Leistungen, Betreuung und hauswirtschaftliche Versorgung. Bei konkreten medizinischen oder Kapazitätsfragen übergebe ich an einen Menschen.');quick([['CN anrufen','call'],['Rückruf vormerken','callback'],['Zurück','start']]);}else if(action==='career'){bot('Aktuell öffentlich gesucht wird eine Pflegefachkraft (m/w/d) in Frankfurt – Vollzeit und unbefristet.');quick([['Job Match öffnen','goto-job'],['E-Mail an CN','mail-job'],['Zurück','start']]);}else if(action==='callback'){bot('Für die Demo können Sie einen gewünschten Zeitraum auswählen. Das ist noch keine bestätigte Buchung.');quick([['Heute Nachmittag','slot-a'],['Morgen Vormittag','slot-b'],['Anderer Kontaktweg','start']]);}else if(action.startsWith('slot-')){bot(`Vorgemerkt als Demo: <strong>${label}</strong>. Im finalen System würde jetzt eine echte Kalender-/Rückrufintegration greifen.`);quick([['Jetzt direkt anrufen','call'],['E-Mail senden','mail-care'],['Neu starten','start']]);}else if(action==='call'){location.href='tel:+496996237272'}else if(action==='mail-job'){location.href='mailto:info@cn-derpflegedienst.de?subject=Interesse%20Pflegefachkraft'}else if(action==='mail-care'){location.href='mailto:info@cn-derpflegedienst.de?subject=Pflegeanfrage'}else if(action==='goto-care'){closeChat();location.hash='pflege'}else if(action==='goto-job'){closeChat();location.hash='karriere'}else if(action==='start'){resetChat('start')}}
function openChat(mode='start'){panel.classList.add('open');backdrop.classList.add('open');panel.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';resetChat(mode)}
function closeChat(){panel.classList.remove('open');backdrop.classList.remove('open');panel.setAttribute('aria-hidden','true');document.body.style.overflow=''}
qa('[data-open-chat]').forEach(b=>b.addEventListener('click',()=>openChat('start')));q('[data-close-chat]')?.addEventListener('click',closeChat);backdrop?.addEventListener('click',closeChat);addEventListener('keydown',e=>{if(e.key==='Escape')closeChat()});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){import('lenis').then(({default:Lenis})=>{const lenis=new Lenis({lerp:.18,smoothWheel:true,anchors:true});const loop=t=>{lenis.raf(t);requestAnimationFrame(loop)};requestAnimationFrame(loop);}).catch(()=>{});import('motion').then(({animate})=>{const shape=q('.hero-media-shape');if(shape)animate(shape,{rotate:360},{duration:22,repeat:Infinity,ease:'linear'});qa('.service-row').forEach(row=>{row.addEventListener('pointerenter',()=>animate(row,{x:6},{duration:.2}));row.addEventListener('pointerleave',()=>animate(row,{x:0},{duration:.2}));});}).catch(()=>{});}
