(() => {
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const pageProgress=$('#emProgress');
  const updateProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(pageProgress)pageProgress.style.width=(max>0?Math.min(100,scrollY/max*100):0)+'%'};
  addEventListener('scroll',updateProgress,{passive:true});updateProgress();
  if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.1,rootMargin:'0px 0px -6% 0px'});$$('.em-section,.em-photo,.em-service-list article,.v3-route,.v3-employer-grid article').forEach(el=>{el.classList.add('em-reveal');io.observe(el)})}
  const params=new URLSearchParams(location.search), attribution=[params.get('utm_source'),params.get('utm_campaign')].filter(Boolean).join(' / ');
  const smoothTo=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});
  $$('.v3-route').forEach(btn=>btn.addEventListener('click',()=>{const r=btn.dataset.route;if(r==='career')return smoothTo('job-match');smoothTo('pflege-kompass');setTimeout(()=>{const v=r==='relative'?'Für einen Angehörigen':'Für mich selbst';document.querySelector(`[data-care-key="person"][data-care-value="${v}"]`)?.focus({preventScroll:true})},650)}));
  const buildFlow=({root,screenSelector,stepLabel,progress,back,restart,answerSelector,summary,mail,copy,kind})=>{
    const screens=$$(screenSelector,root), state={};let step=0;const total=screens.length;
    const labels=kind==='care'?{person:'Für wen',need:'Worum es geht',urgency:'Dringlichkeit',contact:'Kontaktwunsch'}:{priority:'Wichtig beim Wechsel',qualification:'Hintergrund',hours:'Arbeitszeit',timing:'Zeitpunkt'};
    const summaryText=()=>Object.entries(labels).filter(([k])=>state[k]).map(([k,l])=>`${l}: ${state[k]}`).join('\n');
    const updateResult=()=>{if(!summary)return;summary.innerHTML='<ul>'+Object.entries(labels).filter(([k])=>state[k]).map(([k,l])=>`<li><b>${l}</b><span>${state[k]}</span></li>`).join('')+'</ul>';const intro=kind==='care'?'Guten Tag CN-Team,\n\nich habe den Pflege-Check auf Ihrer Website genutzt. Meine Situation:\n\n':'Guten Tag CN-Team,\n\nich interessiere mich für die ausgeschriebene Stelle als Pflegefachkraft (m/w/d). Mein kurzer Job-Match:\n\n';const close=kind==='care'?'\n\nIch würde das gerne persönlich mit Ihnen besprechen.\n\nViele Grüße':'\n\nIch würde CN gerne kennenlernen und die offenen Punkte persönlich besprechen.\n\nViele Grüße';const meta=attribution?`\n\nQuelle: ${attribution}`:'';if(mail){const subject=kind==='care'?'Anfrage über den CN Pflege-Check':'Interesse an der Stelle als Pflegefachkraft';mail.href=`mailto:info@cn-derpflegedienst.de?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(intro+summaryText()+meta+close)}`}};
    const render=()=>{screens.forEach((s,i)=>s.classList.toggle('active',i===step));if(stepLabel)stepLabel.textContent=String(step+1).padStart(2,'0')+' / '+String(total).padStart(2,'0');if(progress)progress.style.width=(((step+1)/total)*100)+'%';if(back)back.disabled=step===0;if(restart)restart.style.visibility=step===0?'hidden':'visible';if(step===total-1)updateResult()};
    $$(answerSelector,root).forEach(btn=>btn.addEventListener('click',()=>{const key=kind==='care'?btn.dataset.careKey:btn.dataset.jobKey,value=kind==='care'?btn.dataset.careValue:btn.dataset.jobValue;if(key)state[key]=value;if(step<total-1){step++;render()}}));
    back?.addEventListener('click',()=>{if(step>0){step--;render()}});restart?.addEventListener('click',()=>{Object.keys(state).forEach(k=>delete state[k]);step=0;render();root.scrollIntoView({behavior:'smooth',block:'center'})});copy?.addEventListener('click',async()=>{const text=summaryText();try{await navigator.clipboard.writeText(text);const old=copy.textContent;copy.textContent='Kopiert ✓';copy.classList.add('copied');setTimeout(()=>{copy.textContent=old;copy.classList.remove('copied')},1800)}catch{copy.textContent='Bitte Zusammenfassung markieren'}});render();return{state,setInitial(k,v){state[k]=v},go(n){step=Math.max(0,Math.min(total-1,n));render()}};
  };
  let careFlow;const careRoot=$('#careFlow');if(careRoot)careFlow=buildFlow({root:careRoot,screenSelector:'.v3-screen[data-care-step]',stepLabel:$('#careStepLabel'),progress:$('#careProgress'),back:$('#careBack'),restart:$('#careRestart'),answerSelector:'button[data-care-key]',summary:$('#careSummary'),mail:$('#careMail'),copy:$('#careCopy'),kind:'care'});
  const jobRoot=$('#jobFlow');if(jobRoot)buildFlow({root:jobRoot,screenSelector:'.v3-screen[data-job-step]',stepLabel:$('#jobStepLabel'),progress:$('#jobProgress'),back:$('#jobBack'),restart:$('#jobRestart'),answerSelector:'button[data-job-key]',summary:$('#jobSummary'),mail:$('#jobMail'),copy:$('#jobCopy'),kind:'job'});
  const intent=params.get('intent');if(intent==='career')setTimeout(()=>smoothTo('job-match'),250);if(intent==='relative'||intent==='self'){careFlow?.setInitial('person',intent==='relative'?'Für einen Angehörigen':'Für mich selbst');careFlow?.go(1);setTimeout(()=>smoothTo('pflege-kompass'),250)}
})();