const services = [
  ["01", "Grundpflege", "Unterstützung bei den täglichen Dingen des Lebens – respektvoll, verlässlich und auf den persönlichen Bedarf abgestimmt."],
  ["02", "Behandlungspflege", "Medizinische Versorgung nach ärztlicher Verordnung – professionell im vertrauten Zuhause durchgeführt."],
  ["03", "Betreuung", "Begleitung im Alltag und persönliche Zuwendung, damit Selbstständigkeit und Lebensqualität möglichst lange erhalten bleiben."],
  ["04", "Hauswirtschaft", "Praktische Entlastung im Haushalt – damit mehr Kraft für die wichtigen Dinge des Alltags bleibt."]
];

const Arrow = () => <span aria-hidden="true">→</span>;

export default function Home() {
  return (
    <main>
      <div className="topbar"><div className="shell"><span>Ambulanter Pflegedienst in Frankfurt am Main</span><a href="tel:+496996237272">069 962 37 272</a></div></div>
      <header><div className="shell nav"><a className="brand" href="#start"><b>CN</b><span><strong>DER PFLEGEDIENST</strong><small>Frankfurt am Main</small></span></a><nav><a href="#leistungen">Leistungen</a><a href="#ueber-uns">Über uns</a><a href="#ablauf">So geht’s</a><a href="#kontakt">Kontakt</a></nav><a className="pill outline" href="tel:+496996237272">Erstgespräch</a></div></header>

      <section className="hero" id="start"><div className="shell heroGrid"><div className="heroCopy"><span className="eyebrow">Persönlich. Verlässlich. Zuhause.</span><h1>Pflege, die sich nach <em>Ihrem Leben</em> richtet.</h1><p>CN begleitet Menschen in Frankfurt dort, wo sie sich am wohlsten fühlen: im eigenen Zuhause. Mit professioneller Pflege, persönlicher Betreuung und einem offenen Ohr für Angehörige.</p><div className="actions"><a className="pill dark" href="tel:+496996237272">Kostenlos beraten lassen</a><a className="link" href="#leistungen">Unsere Leistungen <Arrow /></a></div><div className="trust"><span>✓ Ambulant in Frankfurt</span><span>✓ Individuelle Versorgung</span><span>✓ Persönlicher Kontakt</span></div></div><div className="heroVisual"><div className="photo"><img src="https://images.unsplash.com/photo-1543333995-a78aea2eee50?auto=format&fit=crop&w=1600&q=85" alt="Ältere Frau im Rollstuhl mit vertrauter Begleitung" /></div><div className="quoteCard"><i>♡</i><div><strong>Pflege beginnt mit Zuhören.</strong><small>Wir nehmen uns Zeit für den Menschen hinter dem Pflegebedarf.</small></div></div></div></div><div className="shell heroMeta"><span>CN – Der Pflegedienst</span><i></i><span>Frankfurt · Sachsenhausen</span></div></section>

      <section className="section services" id="leistungen"><div className="shell"><div className="sectionHead"><div><span className="eyebrow">Was wir für Sie tun</span><h2>Unterstützung, die im Alltag wirklich hilft.</h2></div><p>Pflege ist so individuell wie der Mensch selbst. Deshalb schauen wir gemeinsam, welche Unterstützung zuhause wirklich gebraucht wird.</p></div><div className="serviceGrid">{services.map(([n,t,d]) => <article key={t}><div className="serviceTop"><span className="serviceIcon">♡</span><span>{n}</span></div><h3>{t}</h3><p>{d}</p><a href="#kontakt">Leistung anfragen <Arrow /></a></article>)}</div><small className="note">Das konkrete Leistungsangebot wird im persönlichen Gespräch auf Ihren Bedarf abgestimmt.</small></div></section>

      <section className="manifesto section" id="ueber-uns"><div className="shell manifestoGrid"><div className="monogram" aria-hidden="true">CN</div><div><span className="eyebrow light">Unser Verständnis von Pflege</span><h2>Nicht irgendein Alltag. <em>Ihr Alltag.</em></h2><p>Gute ambulante Pflege soll Sicherheit geben, ohne das eigene Leben aus der Hand zu nehmen. Sie soll entlasten, ohne zu bevormunden. Und sie soll Angehörigen das Gefühl geben, einen verlässlichen Ansprechpartner an ihrer Seite zu haben.</p><blockquote>„So viel Unterstützung wie nötig. So viel Selbstständigkeit wie möglich.“</blockquote><small>CN – Der Pflegedienst</small></div></div></section>

      <section className="section process" id="ablauf"><div className="shell processGrid"><div className="processIntro"><span className="eyebrow">Einfach starten</span><h2>Von der ersten Frage zur passenden Unterstützung.</h2><p>Ein Pflegebedarf wirft oft viele Fragen auf. Unser Ziel: den nächsten Schritt klar und unkompliziert machen.</p><a className="pill dark" href="tel:+496996237272">069 962 37 272</a></div><ol>{[["01","Kontakt aufnehmen","Rufen Sie uns an oder schreiben Sie eine E-Mail. Erzählen Sie uns kurz, wobei Sie Unterstützung benötigen."],["02","Bedarf besprechen","Gemeinsam klären wir, welche Form der Versorgung zu Ihrer Situation und Ihrem Alltag passt."],["03","Versorgung abstimmen","Die nächsten Schritte werden transparent vereinbart – persönlich und auf den tatsächlichen Bedarf ausgerichtet."]].map(([n,t,d]) => <li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></div></section>

      <section className="location"><div className="shell locationCard"><div><span className="eyebrow light">Zuhause in Frankfurt</span><h2>Kurze Wege. Persönlicher Kontakt.</h2><p>Sie finden CN – Der Pflegedienst in der Mörfelder Landstraße 64 in Frankfurt-Sachsenhausen.</p></div><div className="address"><small>CN – Der Pflegedienst</small><strong>Mörfelder Landstr. 64<br/>60598 Frankfurt am Main</strong><a target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=M%C3%B6rfelder+Landstr.+64+60598+Frankfurt+am+Main">Route öffnen <Arrow /></a></div></div></section>

      <section className="section contact" id="kontakt"><div className="shell contactGrid"><div><span className="eyebrow">Wir sind für Sie da</span><h2>Der erste Schritt darf einfach sein.</h2><p>Sie haben Fragen zur ambulanten Pflege oder möchten wissen, welche Unterstützung infrage kommt? Sprechen Sie direkt mit uns.</p></div><div className="contactRows"><a href="tel:+496996237272"><span>Telefon</span><strong>069 962 37 272</strong><Arrow /></a><a href="mailto:info@cn-derpflegedienst.de"><span>E-Mail</span><strong>info@cn-derpflegedienst.de</strong><Arrow /></a></div></div></section>

      <footer><div className="shell footerGrid"><div><a className="brand invert" href="#start"><b>CN</b><span><strong>DER PFLEGEDIENST</strong><small>Frankfurt am Main</small></span></a><p>Ambulante Pflege und Unterstützung für Menschen in Frankfurt am Main.</p></div><div><h4>Kontakt</h4><a href="tel:+496996237272">069 962 37 272</a><a href="mailto:info@cn-derpflegedienst.de">info@cn-derpflegedienst.de</a></div><div><h4>Adresse</h4><p>Mörfelder Landstr. 64<br/>60598 Frankfurt am Main</p></div><div><h4>Rechtliches</h4><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a></div></div></footer>
    </main>
  );
}
